CREATE TABLE DTIPOBAIRRO( 
      `DESCRICAO` varchar  (20)   NOT NULL  , 
      `CODIGO`  INT  AUTO_INCREMENT    NOT NULL  , 
      `RECCREATEDBY` varchar  (50)   , 
      `RECCREATEDON` datetime   , 
      `RECMODIFIEDBY` varchar  (50)   , 
      `RECMODIFIEDON` datetime   , 
 PRIMARY KEY (CODIGO)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE DTIPORUA( 
      `DESCRICAO` varchar  (20)   NOT NULL  , 
      `CODIGO`  INT  AUTO_INCREMENT    NOT NULL  , 
      `RECCREATEDBY` varchar  (50)   , 
      `RECCREATEDON` datetime   , 
      `RECMODIFIEDBY` varchar  (50)   , 
      `RECMODIFIEDON` datetime   , 
 PRIMARY KEY (CODIGO)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE FCFO( 
      `id`  INT  AUTO_INCREMENT    NOT NULL  , 
      `CODCFO` varchar  (25)   NOT NULL  , 
      `USE` text   NOT NULL  , 
      `NOMEFANTASIA` varchar  (100)   , 
      `NOME` varchar  (100)   , 
      `CGCCFO` varchar  (20)   , 
      `PAGREC` int   NOT NULL  , 
      `RUA` varchar  (100)   , 
      `NUMERO` varchar  (8)   , 
      `COMPLEMENTO` text   , 
      `BAIRRO` text   , 
      `CIDADE` text   , 
      `CODETD` varchar  (2)   , 
      `CEP` text   , 
      `TELEFONE` varchar  (15)   , 
      `RUAPGTO` varchar  (100)   , 
      `NUMEROPGTO` varchar  (8)   , 
      `COMPLEMENTOPGTO` text   , 
      `BAIRROPGTO` text   , 
      `CIDADEPGTO` text   , 
      `CODETDPGTO` varchar  (2)   , 
      `CEPPGTO` text   , 
      `TELEFONEPGTO` varchar  (15)   , 
      `RUAENTREGA` varchar  (100)   , 
      `NUMEROENTREGA` varchar  (8)   , 
      `COMPLEMENTREGA` text   , 
      `BAIRROENTREGA` text   , 
      `CIDADEENTREGA` text   , 
      `CODETDENTREGA` varchar  (2)   , 
      `CEPENTREGA` text   , 
      `TELEFONEENTREGA` varchar  (15)   , 
      `FAX` varchar  (15)   , 
      `TELEX` varchar  (15)   , 
      `EMAIL` varchar  (250)   , 
      `CONTATO` varchar  (40)   , 
      `CODTCF` varchar  (25)   , 
      `ATIVO` int   NOT NULL  , 
      `LIMITECREDITO` text   , 
      `VALORULTIMOLAN` text   , 
      `TIPOINSCRCNAB` int   , 
      `DATAULTALTERACAO` datetime   , 
      `DATACRIACAO` datetime   , 
      `DATAULTMOVIMENTO` datetime   , 
      `CONTEVENTOCONTAB` int   , 
      `CAMPOLIVRE` varchar  (40)   , 
      `CAMPOALFAOP1` varchar  (40)   , 
      `CAMPOALFAOP2` varchar  (40)   , 
      `CAMPOALFAOP3` varchar  (40)   , 
      `VALOROP1` text   , 
      `VALOROP2` text   , 
      `VALOROP3` text   , 
      `DATAOP1` datetime   , 
      `DATAOP2` datetime   , 
      `DATAOP3` datetime   , 
      `CODTRA` varchar  (5)   , 
      `CHAPA` varchar  (16)   , 
      `STATUSCOTACAO` varchar  (1)   , 
      `DTINICATIVIDADES` datetime   , 
      `PATRIMONIO` text   , 
      `NUMFUNCIONARIOS` int   , 
      `CODCOLCHAVESESTRANG` int   , 
      `CODCOLTCF` int   , 
      `FAXDEDICADO` int   , 
      `CODMUNICIPIO` varchar  (20)   , 
      `CODCOLCONTAGER` int   , 
      `CODCONTAGER` text   , 
      `FORMAPAGAMENTO` int   , 
      `IDENTPORCNPJ` text   , 
      `INSCRMUNICIPAL` varchar  (20)   , 
      `PESSOAFISOUJUR` varchar  (1)   NOT NULL  , 
      `CONTATOPGTO` varchar  (40)   , 
      `CONTATOENTREGA` varchar  (40)   , 
      `PAIS` varchar  (20)   , 
      `PAISPAGTO` varchar  (20)   , 
      `PAISENTREGA` varchar  (20)   , 
      `ULTIMODOCUMENTO` varchar  (40)   , 
      `CONTRIBUINTE` int   , 
      `CFOIMOB` int   , 
      `TIPODOC` varchar  (1)   , 
      `CODFINALIDADE` int   , 
      `AGRUPCOB` char  (1)   , 
      `CODCARGO` varchar  (3)   , 
      `CODVINCULO` char  (1)   , 
      `ENDCOBC` char  (1)   , 
      `CIDENTIDADE` varchar  (20)   , 
      `CI_ORGAO` varchar  (15)   , 
      `CI_UF` varchar  (2)   , 
      `CODPROF` int   , 
      `CODPAGTOGPS` varchar  (5)   , 
      `FAXENTREGA` varchar  (15)   , 
      `EMAILENTREGA` varchar  (250)   , 
      `FAXPGTO` varchar  (15)   , 
      `EMAILPGTO` varchar  (250)   , 
      `SATISFACAO` int   , 
      `VALFRETE` text   , 
      `TPTOMADOR` int   , 
      `CONTRIBUINTEISS` int   , 
      `NUMDEPENDENTES` int   , 
      `EMPRESA` varchar  (60)   , 
      `ESTADOCIVIL` varchar  (1)   , 
      `CODCOLCXA` text   , 
      `CODCXA` varchar  (10)   , 
      `PRODUTORRURAL` boolean   , 
      `USUARIOALTERACAO` varchar  (20)   , 
      `SUFRAMA` varchar  (14)   , 
      `CODMUNICIPIOPGTO` varchar  (20)   , 
      `CODMUNICIPIOENTREGA` varchar  (20)   , 
      `ORGAOPUBLICO` int   , 
      `TELEFONECOMERCIAL` varchar  (15)   , 
      `CAIXAPOSTAL` varchar  (10)   , 
      `CAIXAPOSTALENTREGA` varchar  (10)   , 
      `CAIXAPOSTALPAGAMENTO` varchar  (10)   , 
      `CATEGORIAAUTONOMO` int   , 
      `CBOAUTONOMO` varchar  (10)   , 
      `CIAUTONOMO` varchar  (11)   , 
      `IDCFO` int   NOT NULL  , 
      `CODIGOINSS` varchar  (10)   , 
      `VROUTRASDEDUCOESIRRF` text   , 
      `CODRECEITA` varchar  (10)   , 
      `CEI` varchar  (20)   , 
      `OPTANTEPELOSIMPLES` int   , 
      `TIPORUA` int   , 
      `TIPOBAIRRO` int   , 
      `REGIMEISS` varchar  (1)   , 
      `RETENCAOISS` int   , 
      `DTNASCIMENTO` datetime   , 
      `USUARIOCRIACAO` varchar  (20)   , 
      `TIPOOPCOMBUSTIVEL` int   , 
      `INSCRESTADUALST` varchar  (20)   , 
      `LOCALIDADE` varchar  (40)   , 
      `LOCALIDADEPGTO` varchar  (40)   , 
      `LOCALIDADEENTREGA` varchar  (40)   , 
      `TIPORUAPGTO` int   , 
      `TIPORUAENTREGA` int   , 
      `TIPOBAIRROPGTO` int   , 
      `TIPOBAIRROENTREGA` int   , 
      `PORTE` int   , 
      `RAMOATIV` int   NOT NULL  , 
      `NIT` varchar  (15)   , 
      `CEPCAIXAPOSTAL` text   , 
      `NUMDIASATRASO` int   , 
      `IDPAIS` int   , 
      `IDPAISPGTO` int   , 
      `IDPAISENTREGA` int   , 
      `TIPOCONTRIBUINTEINSS` int   NOT NULL  , 
      `NACIONALIDADE` int   NOT NULL  , 
      `CODCOLCFOFISCAL` text   , 
      `IDCFOFISCAL` int   , 
      `EMAILFISCAL` varchar  (250)   , 
      `CALCULAAVP` int   NOT NULL  , 
      `CODUSUARIOACESSO` varchar  (20)   , 
      `RECCREATEDBY` varchar  (50)   , 
      `RECCREATEDON` datetime   , 
      `RECMODIFIEDBY` varchar  (50)   , 
      `RECMODIFIEDON` datetime   , 
      `IDINTEGRACAO` varchar  (100)   , 
      `USARCUMULATRETENCAOPAGAR` int   , 
      `NIF` varchar  (50)   , 
      `SITUACAONIF` int   , 
      `TIPORENDIMENTO` varchar  (3)   , 
      `FORMATRIBUTACAO` varchar  (2)   , 
      `INDNATRET` varchar  (5)   , 
      `DOCUMENTOESTRANGEIRO` varchar  (30)   , 
      `TPLOTACAO_OLD` varchar  (2)   , 
      `INOVAR_AUTO` int   , 
      `FILIALFINANCEIRA` int   , 
      `TOMADORFOLHA` int   , 
      `CNAEPREP` varchar  (7)   , 
      `PERCENTACIDTRAB` text   , 
      `CODCOLFORMULA` text   , 
      `FORMULAVALDEDUCAOVARIAVEL` varchar  (8)   , 
      `APLICFORMULA` varchar  (1)   , 
      `CODCFOCOLINTEGRACAO` text   , 
      `CODCFOINTEGRACAO` varchar  (25)   , 
      `DIGVERIFICDEBAUTOMATICO` varchar  (1)   , 
      `CODLOJA` varchar  (8)   , 
      `CODFILIALINTEGRACAO` int   , 
      `CODEXTERNO` varchar  (25)   , 
      `TIPOCLIENTE` varchar  (2)   , 
      `CONSIDERAFILIALOBRA` int   , 
      `CODFILIALOBRA` int   , 
      `TIPOCONTROLEPONTO` int   , 
      `FAP` text   , 
      `CODCOLIGADAFILIALOBRA` text   , 
      `OBRAPROPRIA` int   , 
      `ENTIDADEEXECUTORAPAA` int   NOT NULL  , 
      `APOSENTADOOUPENSIONISTA` int   NOT NULL  , 
      `CODCATEGORIAESOCIAL` int   , 
      `CNPJRURAL` varchar  (20)   , 
      `CODIGOCAEPF` varchar  (18)   , 
      `ISENTOTRIBUTOS` text   , 
      `SOCIOCOOPERADO` int   NOT NULL  , 
 PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE FCFOCONTATO( 
      `IDINTEGRACAO`  INT  AUTO_INCREMENT    NOT NULL  , 
      `IDCONTATO` int   NOT NULL  , 
      `CODCOLIGADA` text   NOT NULL  , 
      `CODCFO` varchar  (25)   NOT NULL  , 
      `NOME` varchar  (50)   NOT NULL  , 
      `EMAIL` varchar  (80)   , 
      `TELEFONE` varchar  (15)   , 
      `RAMAL` varchar  (6)   , 
      `FAX` varchar  (15)   , 
      `FUNCAO` varchar  (50)   , 
      `OBSERVACAO` varchar  (80)   , 
      `CODUSUARIO` varchar  (20)   , 
      `RUA` varchar  (100)   , 
      `NUMERO` varchar  (8)   , 
      `COMPLEMENTO` text   , 
      `BAIRRO` text   , 
      `CIDADE` text   , 
      `CODETD` varchar  (2)   , 
      `CEP` text   , 
      `PAIS` varchar  (20)   , 
      `USUARIOALTERACAO` varchar  (20)   , 
      `DATAALTERACAO` datetime   , 
      `ATIVO` int   , 
      `DATANASCIMENTO` datetime   , 
      `DEFAUTPARAEMAIL` int   , 
      `CODAPLIC` varchar  (2)   , 
      `CODMUNICIPIO` varchar  (20)   , 
      `LOCALIDADE` varchar  (40)   , 
      `CODUSUARIOACESSO` varchar  (20)   , 
      `RECCREATEDBY` varchar  (50)   , 
      `RECCREATEDON` datetime   , 
      `RECMODIFIEDBY` varchar  (50)   , 
      `RECMODIFIEDON` datetime   , 
 PRIMARY KEY (IDINTEGRACAO)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE FCFODEF( 
      `CODCOLIGADA` text   NOT NULL  , 
      `id`  INT  AUTO_INCREMENT    NOT NULL  , 
      `CODCFO` varchar  (25)   NOT NULL  , 
      `CODTB1FLX` varchar  (25)   , 
      `CODTB2FLX` varchar  (25)   , 
      `CODTB3FLX` varchar  (25)   , 
      `CODTB4FLX` varchar  (25)   , 
      `CODTB5FLX` varchar  (25)   , 
      `CODDEPARTAMENTO` varchar  (25)   , 
      `CODCCUSTO` varchar  (25)   , 
      `CODFILIAL` int   , 
      `CODCOLCFO` text   NOT NULL  , 
      `CODBANCOCOBRANCA` varchar  (3)   , 
      `CNABCARTEIRA` int   , 
      `CODCPG` varchar  (5)   , 
      `CODVEN` varchar  (16)   , 
      `PERCENTUALDESC` text   , 
      `CODRPR` varchar  (15)   , 
      `CODTDO` varchar  (10)   , 
      `CODCOLCXA` text   , 
      `CODCXA` varchar  (10)   , 
      `CODTRA` varchar  (5)   , 
      `TIPOCONTABILLAN` int   , 
      `CODCPGVENDA` varchar  (5)   , 
      `CIFFOB` int   , 
      `CODTRA2` varchar  (5)   , 
      `DIASVENCSEMANA` int   , 
      `PERCDESCCOMPRA` text   , 
      `CODIGOINSS` varchar  (10)   , 
      `RECCREATEDBY` varchar  (50)   , 
      `RECCREATEDON` datetime   , 
      `RECMODIFIEDBY` varchar  (50)   , 
      `RECMODIFIEDON` datetime   , 
      `IDITEMCONTABIL` int   , 
      `IDCONVENIO` int   , 
 PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE FTCF( 
      `CODCOLIGADA` text   NOT NULL  , 
      `id`  INT  AUTO_INCREMENT    NOT NULL  , 
      `CODTCF` varchar  (25)   NOT NULL  , 
      `DESCRICAO` varchar  (40)   , 
      `CAMPOLIVRE` varchar  (40)   , 
      `CODSEGM` varchar  (5)   , 
      `RECCREATEDBY` varchar  (50)   , 
      `RECCREATEDON` datetime   , 
      `RECMODIFIEDBY` varchar  (50)   , 
      `RECMODIFIEDON` datetime   , 
 PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE GCCUSTO( 
      `USE` text   NOT NULL  , 
      `ID`  INT  AUTO_INCREMENT    NOT NULL  , 
      `CODCCUSTO` varchar  (25)   NOT NULL  , 
      `NOME` varchar  (60)   , 
      `CODCOLCONTAGER` text   , 
      `CODCONTAGER` text   , 
      `CODCOLCONTA` text   , 
      `CODCONTA` text   , 
      `CODREDUZIDO` varchar  (25)   NOT NULL  , 
      `CAMPOLIVRE` varchar  (100)   , 
      `ATIVO` boolean   , 
      `PERMITELANC` boolean   , 
      `CODCLASSIFICA` varchar  (10)   , 
      `ENVIASPED` boolean   NOT NULL  , 
      `DATAINCLUSAO` datetime   , 
      `RECCREATEDBY` varchar  (50)   , 
      `RECCREATEDON` datetime   , 
      `RECMODIFIEDBY` varchar  (50)   , 
      `RECMODIFIEDON` datetime   , 
      `RESPONSAVEL` int   , 
 PRIMARY KEY (ID)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE GETD( 
      `id`  INT  AUTO_INCREMENT    NOT NULL  , 
      `CODETD` varchar  (2)   NOT NULL  , 
      `NOME` varchar  (40)   , 
      `NACIONAL` varchar  (1)   , 
      `CODIGOSINIEF` varchar  (4)   , 
      `IDPAIS` int   , 
      `RECCREATEDBY` varchar  (50)   , 
      `RECCREATEDON` datetime   , 
      `RECMODIFIEDBY` varchar  (50)   , 
      `RECMODIFIEDON` datetime   , 
 PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE GMUNICIPIO( 
      `id`  INT  AUTO_INCREMENT    NOT NULL  , 
      `CODMUNICIPIO` varchar  (20)   NOT NULL  , 
      `CODETDMUNICIPIO` varchar  (2)   NOT NULL  , 
      `NOMEMUNICIPIO` varchar  (32)   , 
      `RECCREATEDBY` varchar  (50)   , 
      `RECCREATEDON` datetime   , 
      `RECMODIFIEDBY` varchar  (50)   , 
      `RECMODIFIEDON` datetime   , 
 PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE GPAIS( 
      `IDPAIS`  INT  AUTO_INCREMENT    NOT NULL  , 
      `CODPAIS` varchar  (5)   NOT NULL  , 
      `DESCRICAO` varchar  (60)   , 
      `RECCREATEDBY` varchar  (50)   , 
      `RECCREATEDON` datetime   , 
      `RECMODIFIEDBY` varchar  (50)   , 
      `RECMODIFIEDON` datetime   , 
 PRIMARY KEY (IDPAIS)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE orcamentos_cnc( 
      `row_num`  INT  AUTO_INCREMENT    , 
      `coligada` varchar  (255)   , 
      `orcamento` varchar  (255)   , 
      `data_emissao` date   , 
      `cod_cliente` char  (7)   , 
      `cliente` varchar  (255)   , 
      `dias` int   , 
      `id_objeto` varchar  (255)   , 
      `objeto` varchar  (255)   , 
      `centro_custo` varchar  (255)   , 
      `os` varchar  (255)   , 
      `tecnico` varchar  (255)   , 
      `status` varchar  (255)   , 
      `cor_status` varchar  (10)   , 
      `intervalo` varchar  (20)   , 
      `qtde` int   , 
 PRIMARY KEY (row_num)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE orcamentos_comercio( 
      `row_num`  INT  AUTO_INCREMENT    , 
      `coligada` varchar  (255)   , 
      `orcamento` varchar  (255)   , 
      `data_emissao` date   , 
      `cod_cliente` char  (7)   , 
      `cliente` varchar  (255)   , 
      `dias` int   , 
      `id_objeto` varchar  (255)   , 
      `objeto` varchar  (255)   , 
      `centro_custo` varchar  (255)   , 
      `os` varchar  (255)   , 
      `tecnico` varchar  (255)   , 
      `status` varchar  (255)   , 
      `cor_status` varchar  (10)   , 
      `intervalo` varchar  (25)   , 
      `qtde` int   , 
 PRIMARY KEY (row_num)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE TCPG( 
      `id`  INT  AUTO_INCREMENT    NOT NULL  , 
      `CODCOLIGADA` text   NOT NULL  , 
      `CODCPG` varchar  (5)   NOT NULL  , 
      `NOME` varchar  (100)   , 
      `ARREDPRIMOUULT` varchar  (1)   , 
      `ARREDDEZOUCENT` varchar  (1)   , 
      `NUMVETCONDICOES` int   , 
      `VALORPAGAMENTO1` text   , 
      `QUANTASVEZES1` int   , 
      `PERIODOEMDIAS1` int   , 
      `PRAZO1` int   , 
      `CONTAGEMDIAS1` varchar  (1)   , 
      `TIPO1` varchar  (1)   , 
      `VALORPAGAMENTO2` text   , 
      `QUANTASVEZES2` int   , 
      `PERIODOEMDIAS2` int   , 
      `PRAZO2` int   , 
      `CONTAGEMDIAS2` varchar  (1)   , 
      `TIPO2` varchar  (1)   , 
      `VALORPAGAMENTO3` text   , 
      `QUANTASVEZES3` int   , 
      `PERIODOEMDIAS3` int   , 
      `PRAZO3` int   , 
      `CONTAGEMDIAS3` varchar  (1)   , 
      `TIPO3` varchar  (1)   , 
      `VALORPAGAMENTO4` text   , 
      `QUANTASVEZES4` int   , 
      `PERIODOEMDIAS4` int   , 
      `PRAZO4` int   , 
      `CONTAGEMDIAS4` varchar  (1)   , 
      `TIPO4` varchar  (1)   , 
      `VALORPAGAMENTO5` text   , 
      `QUANTASVEZES5` int   , 
      `PERIODOEMDIAS5` int   , 
      `PRAZO5` int   , 
      `CONTAGEMDIAS5` varchar  (1)   , 
      `TIPO5` varchar  (1)   , 
      `DEFLATOR` text   , 
      `APLICACAOFRM` varchar  (1)   , 
      `CODFRMPRECO1` varchar  (8)   , 
      `CODFRMPRECO2` varchar  (8)   , 
      `DIACARENCIA` int   , 
      `TAXAJUROS` text   , 
      `JUROSCOMPOSTO` text   , 
      `PLANOPAGTO` int   , 
      `CAPITALIZMENSAL` text   , 
      `PLANOCOMPRA` text   , 
      `PLANOVENDA` text   , 
      `DIASVENCSEMANA` int   , 
      `CODFRMPRIMPARCELA` varchar  (8)   , 
      `INATIVO` int   , 
      `RECCREATEDBY` varchar  (50)   , 
      `RECCREATEDON` datetime   , 
      `RECMODIFIEDBY` varchar  (50)   , 
      `RECMODIFIEDON` datetime   , 
      `IDFORMAPAGTO` int   , 
 PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE TRPR( 
      `id`  INT  AUTO_INCREMENT    NOT NULL  , 
      `CODCOLIGADA` text   NOT NULL  , 
      `CODRPR` varchar  (15)   NOT NULL  , 
      `NOME` varchar  (40)   , 
      `SIGLA` varchar  (5)   , 
      `NOMEFANTASIA` varchar  (20)   , 
      `RUA` varchar  (100)   , 
      `NUMERO` int   , 
      `COMPLEMENTO` text   , 
      `BAIRRO` text   , 
      `CIDADE` text   , 
      `CODETD` varchar  (2)   , 
      `CEP` text   , 
      `CGC` varchar  (20)   , 
      `INSCRESTADUAL` varchar  (20)   , 
      `CONTATO` varchar  (20)   , 
      `TELEFONE` varchar  (15)   , 
      `FAX` varchar  (15)   , 
      `RUAPGTO` varchar  (100)   , 
      `NUMEROPGTO` int   , 
      `COMPLEMENTOPGTO` text   , 
      `BAIRROPGTO` text   , 
      `CIDADEPGTO` text   , 
      `CODETDPGTO` varchar  (2)   , 
      `CEPPGTO` text   , 
      `PERCENTCOMISSAO` text   , 
      `FATCLIENTEDIRETO` int   , 
      `DIAFATURAMENTO` int   , 
      `PERCENTREPASSE` text   , 
      `CODTB1FLX` varchar  (25)   , 
      `CODTB2FLX` varchar  (25)   , 
      `CODTB3FLX` varchar  (25)   , 
      `CODTB4FLX` varchar  (25)   , 
      `CODTB5FLX` varchar  (25)   , 
      `CLCONTABIL` varchar  (15)   , 
      `INATIVO` text   , 
      `HOMEPAGE` varchar  (80)   , 
      `EMAIL` varchar  (40)   , 
      `CELULAR` varchar  (15)   , 
      `PAIS` varchar  (20)   , 
      `CODUSUARIO` varchar  (20)   , 
      `RECCREATEDBY` varchar  (50)   , 
      `RECCREATEDON` datetime   , 
      `RECMODIFIEDBY` varchar  (50)   , 
      `RECMODIFIEDON` datetime   , 
 PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE TTRA( 
      `USE` text   NOT NULL  , 
      `id`  INT  AUTO_INCREMENT    NOT NULL  , 
      `CODTRA` varchar  (5)   NOT NULL  , 
      `NOME` varchar  (40)   , 
      `RUA` varchar  (100)   , 
      `NUMERO` varchar  (8)   , 
      `COMPLEMENTO` text   , 
      `BAIRRO` text   , 
      `CIDADE` text   , 
      `CODETD` varchar  (2)   , 
      `CEP` text   , 
      `CGC` varchar  (20)   , 
      `INSCRESTADUAL` varchar  (20)   , 
      `CONTATO` varchar  (30)   , 
      `TELEFONE` varchar  (15)   , 
      `TELEX` varchar  (15)   , 
      `FAX` varchar  (15)   , 
      `LIVRE` varchar  (20)   , 
      `NOMEFANTASIA` varchar  (60)   , 
      `PAIS` varchar  (20)   , 
      `CEI` varchar  (20)   , 
      `INSCRMUNICIPAL` varchar  (20)   , 
      `INATIVO` int   , 
      `EMAIL` varchar  (60)   , 
      `RECCREATEDBY` varchar  (50)   , 
      `RECCREATEDON` datetime   , 
      `RECMODIFIEDBY` varchar  (50)   , 
      `RECMODIFIEDON` datetime   , 
      `CODMUNICIPIO` varchar  (20)   , 
 PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

CREATE TABLE TVEN( 
      `CODCOLIGADA` text   NOT NULL  , 
      `id`  INT  AUTO_INCREMENT    NOT NULL  , 
      `CODVEN` varchar  (16)   NOT NULL  , 
      `NOME` varchar  (80)   , 
      `CARGO` varchar  (30)   , 
      `CODFILIAL` int   , 
      `CODLOC` varchar  (15)   , 
      `COMISSAO1` text   , 
      `COMISSAO2` text   , 
      `COMISSAO3` text   , 
      `CODPESSOA` int   , 
      `VENDECOMPRA` int   , 
      `CODUSUARIO` varchar  (20)   , 
      `SENHA` varchar  (80)   , 
      `INATIVO` text   , 
      `PFVENDEDOR` text   , 
      `PFCAIXA` text   , 
      `PFSUPERVISOR` text   , 
      `PFGERENTE` text   , 
      `IDFUNCIONARIO` int   NOT NULL  , 
      `COMISSAO4` text   , 
      `DESCMAXIMO` text   , 
      `RECCREATEDBY` varchar  (50)   , 
      `RECCREATEDON` datetime   , 
      `RECMODIFIEDBY` varchar  (50)   , 
      `RECMODIFIEDON` datetime   , 
 PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci; 

 
 