CREATE TABLE DTIPOBAIRRO( 
      DESCRICAO varchar  (20)   NOT NULL  , 
      CODIGO  INT IDENTITY    NOT NULL  , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON datetime2   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON datetime2   , 
 PRIMARY KEY (CODIGO)) ; 

CREATE TABLE DTIPORUA( 
      DESCRICAO varchar  (20)   NOT NULL  , 
      CODIGO  INT IDENTITY    NOT NULL  , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON datetime2   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON datetime2   , 
 PRIMARY KEY (CODIGO)) ; 

CREATE TABLE FCFO( 
      id  INT IDENTITY    NOT NULL  , 
      CODCFO varchar  (25)   NOT NULL  , 
      USE nvarchar(max)   NOT NULL  , 
      NOMEFANTASIA varchar  (100)   , 
      NOME varchar  (100)   , 
      CGCCFO varchar  (20)   , 
      PAGREC int   NOT NULL  , 
      RUA varchar  (100)   , 
      NUMERO varchar  (8)   , 
      COMPLEMENTO nvarchar(max)   , 
      BAIRRO nvarchar(max)   , 
      CIDADE nvarchar(max)   , 
      CODETD varchar  (2)   , 
      CEP nvarchar(max)   , 
      TELEFONE varchar  (15)   , 
      RUAPGTO varchar  (100)   , 
      NUMEROPGTO varchar  (8)   , 
      COMPLEMENTOPGTO nvarchar(max)   , 
      BAIRROPGTO nvarchar(max)   , 
      CIDADEPGTO nvarchar(max)   , 
      CODETDPGTO varchar  (2)   , 
      CEPPGTO nvarchar(max)   , 
      TELEFONEPGTO varchar  (15)   , 
      RUAENTREGA varchar  (100)   , 
      NUMEROENTREGA varchar  (8)   , 
      COMPLEMENTREGA nvarchar(max)   , 
      BAIRROENTREGA nvarchar(max)   , 
      CIDADEENTREGA nvarchar(max)   , 
      CODETDENTREGA varchar  (2)   , 
      CEPENTREGA nvarchar(max)   , 
      TELEFONEENTREGA varchar  (15)   , 
      FAX varchar  (15)   , 
      TELEX varchar  (15)   , 
      EMAIL varchar  (250)   , 
      CONTATO varchar  (40)   , 
      CODTCF varchar  (25)   , 
      ATIVO int   NOT NULL  , 
      LIMITECREDITO nvarchar(max)   , 
      VALORULTIMOLAN nvarchar(max)   , 
      TIPOINSCRCNAB int   , 
      DATAULTALTERACAO datetime2   , 
      DATACRIACAO datetime2   , 
      DATAULTMOVIMENTO datetime2   , 
      CONTEVENTOCONTAB int   , 
      CAMPOLIVRE varchar  (40)   , 
      CAMPOALFAOP1 varchar  (40)   , 
      CAMPOALFAOP2 varchar  (40)   , 
      CAMPOALFAOP3 varchar  (40)   , 
      VALOROP1 nvarchar(max)   , 
      VALOROP2 nvarchar(max)   , 
      VALOROP3 nvarchar(max)   , 
      DATAOP1 datetime2   , 
      DATAOP2 datetime2   , 
      DATAOP3 datetime2   , 
      CODTRA varchar  (5)   , 
      CHAPA varchar  (16)   , 
      STATUSCOTACAO varchar  (1)   , 
      DTINICATIVIDADES datetime2   , 
      PATRIMONIO nvarchar(max)   , 
      NUMFUNCIONARIOS int   , 
      CODCOLCHAVESESTRANG int   , 
      CODCOLTCF int   , 
      FAXDEDICADO int   , 
      CODMUNICIPIO varchar  (20)   , 
      CODCOLCONTAGER int   , 
      CODCONTAGER nvarchar(max)   , 
      FORMAPAGAMENTO int   , 
      IDENTPORCNPJ nvarchar(max)   , 
      INSCRMUNICIPAL varchar  (20)   , 
      PESSOAFISOUJUR varchar  (1)   NOT NULL  , 
      CONTATOPGTO varchar  (40)   , 
      CONTATOENTREGA varchar  (40)   , 
      PAIS varchar  (20)   , 
      PAISPAGTO varchar  (20)   , 
      PAISENTREGA varchar  (20)   , 
      ULTIMODOCUMENTO varchar  (40)   , 
      CONTRIBUINTE int   , 
      CFOIMOB int   , 
      TIPODOC varchar  (1)   , 
      CODFINALIDADE int   , 
      AGRUPCOB char  (1)   , 
      CODCARGO varchar  (3)   , 
      CODVINCULO char  (1)   , 
      ENDCOBC char  (1)   , 
      CIDENTIDADE varchar  (20)   , 
      CI_ORGAO varchar  (15)   , 
      CI_UF varchar  (2)   , 
      CODPROF int   , 
      CODPAGTOGPS varchar  (5)   , 
      FAXENTREGA varchar  (15)   , 
      EMAILENTREGA varchar  (250)   , 
      FAXPGTO varchar  (15)   , 
      EMAILPGTO varchar  (250)   , 
      SATISFACAO int   , 
      VALFRETE nvarchar(max)   , 
      TPTOMADOR int   , 
      CONTRIBUINTEISS int   , 
      NUMDEPENDENTES int   , 
      EMPRESA varchar  (60)   , 
      ESTADOCIVIL varchar  (1)   , 
      CODCOLCXA nvarchar(max)   , 
      CODCXA varchar  (10)   , 
      PRODUTORRURAL bit   , 
      USUARIOALTERACAO varchar  (20)   , 
      SUFRAMA varchar  (14)   , 
      CODMUNICIPIOPGTO varchar  (20)   , 
      CODMUNICIPIOENTREGA varchar  (20)   , 
      ORGAOPUBLICO int   , 
      TELEFONECOMERCIAL varchar  (15)   , 
      CAIXAPOSTAL varchar  (10)   , 
      CAIXAPOSTALENTREGA varchar  (10)   , 
      CAIXAPOSTALPAGAMENTO varchar  (10)   , 
      CATEGORIAAUTONOMO int   , 
      CBOAUTONOMO varchar  (10)   , 
      CIAUTONOMO varchar  (11)   , 
      IDCFO int   NOT NULL  , 
      CODIGOINSS varchar  (10)   , 
      VROUTRASDEDUCOESIRRF nvarchar(max)   , 
      CODRECEITA varchar  (10)   , 
      CEI varchar  (20)   , 
      OPTANTEPELOSIMPLES int   , 
      TIPORUA int   , 
      TIPOBAIRRO int   , 
      REGIMEISS varchar  (1)   , 
      RETENCAOISS int   , 
      DTNASCIMENTO datetime2   , 
      USUARIOCRIACAO varchar  (20)   , 
      TIPOOPCOMBUSTIVEL int   , 
      INSCRESTADUALST varchar  (20)   , 
      LOCALIDADE varchar  (40)   , 
      LOCALIDADEPGTO varchar  (40)   , 
      LOCALIDADEENTREGA varchar  (40)   , 
      TIPORUAPGTO int   , 
      TIPORUAENTREGA int   , 
      TIPOBAIRROPGTO int   , 
      TIPOBAIRROENTREGA int   , 
      PORTE int   , 
      RAMOATIV int   NOT NULL  , 
      NIT varchar  (15)   , 
      CEPCAIXAPOSTAL nvarchar(max)   , 
      NUMDIASATRASO int   , 
      IDPAIS int   , 
      IDPAISPGTO int   , 
      IDPAISENTREGA int   , 
      TIPOCONTRIBUINTEINSS int   NOT NULL  , 
      NACIONALIDADE int   NOT NULL  , 
      CODCOLCFOFISCAL nvarchar(max)   , 
      IDCFOFISCAL int   , 
      EMAILFISCAL varchar  (250)   , 
      CALCULAAVP int   NOT NULL  , 
      CODUSUARIOACESSO varchar  (20)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON datetime2   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON datetime2   , 
      IDINTEGRACAO varchar  (100)   , 
      USARCUMULATRETENCAOPAGAR int   , 
      NIF varchar  (50)   , 
      SITUACAONIF int   , 
      TIPORENDIMENTO varchar  (3)   , 
      FORMATRIBUTACAO varchar  (2)   , 
      INDNATRET varchar  (5)   , 
      DOCUMENTOESTRANGEIRO varchar  (30)   , 
      TPLOTACAO_OLD varchar  (2)   , 
      INOVAR_AUTO int   , 
      FILIALFINANCEIRA int   , 
      TOMADORFOLHA int   , 
      CNAEPREP varchar  (7)   , 
      PERCENTACIDTRAB nvarchar(max)   , 
      CODCOLFORMULA nvarchar(max)   , 
      FORMULAVALDEDUCAOVARIAVEL varchar  (8)   , 
      APLICFORMULA varchar  (1)   , 
      CODCFOCOLINTEGRACAO nvarchar(max)   , 
      CODCFOINTEGRACAO varchar  (25)   , 
      DIGVERIFICDEBAUTOMATICO varchar  (1)   , 
      CODLOJA varchar  (8)   , 
      CODFILIALINTEGRACAO int   , 
      CODEXTERNO varchar  (25)   , 
      TIPOCLIENTE varchar  (2)   , 
      CONSIDERAFILIALOBRA int   , 
      CODFILIALOBRA int   , 
      TIPOCONTROLEPONTO int   , 
      FAP nvarchar(max)   , 
      CODCOLIGADAFILIALOBRA nvarchar(max)   , 
      OBRAPROPRIA int   , 
      ENTIDADEEXECUTORAPAA int   NOT NULL  , 
      APOSENTADOOUPENSIONISTA int   NOT NULL  , 
      CODCATEGORIAESOCIAL int   , 
      CNPJRURAL varchar  (20)   , 
      CODIGOCAEPF varchar  (18)   , 
      ISENTOTRIBUTOS nvarchar(max)   , 
      SOCIOCOOPERADO int   NOT NULL  , 
 PRIMARY KEY (id)) ; 

CREATE TABLE FCFOCONTATO( 
      IDINTEGRACAO  INT IDENTITY    NOT NULL  , 
      IDCONTATO int   NOT NULL  , 
      CODCOLIGADA nvarchar(max)   NOT NULL  , 
      CODCFO varchar  (25)   NOT NULL  , 
      NOME varchar  (50)   NOT NULL  , 
      EMAIL varchar  (80)   , 
      TELEFONE varchar  (15)   , 
      RAMAL varchar  (6)   , 
      FAX varchar  (15)   , 
      FUNCAO varchar  (50)   , 
      OBSERVACAO varchar  (80)   , 
      CODUSUARIO varchar  (20)   , 
      RUA varchar  (100)   , 
      NUMERO varchar  (8)   , 
      COMPLEMENTO nvarchar(max)   , 
      BAIRRO nvarchar(max)   , 
      CIDADE nvarchar(max)   , 
      CODETD varchar  (2)   , 
      CEP nvarchar(max)   , 
      PAIS varchar  (20)   , 
      USUARIOALTERACAO varchar  (20)   , 
      DATAALTERACAO datetime2   , 
      ATIVO int   , 
      DATANASCIMENTO datetime2   , 
      DEFAUTPARAEMAIL int   , 
      CODAPLIC varchar  (2)   , 
      CODMUNICIPIO varchar  (20)   , 
      LOCALIDADE varchar  (40)   , 
      CODUSUARIOACESSO varchar  (20)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON datetime2   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON datetime2   , 
 PRIMARY KEY (IDINTEGRACAO)) ; 

CREATE TABLE FCFODEF( 
      CODCOLIGADA nvarchar(max)   NOT NULL  , 
      id  INT IDENTITY    NOT NULL  , 
      CODCFO varchar  (25)   NOT NULL  , 
      CODTB1FLX varchar  (25)   , 
      CODTB2FLX varchar  (25)   , 
      CODTB3FLX varchar  (25)   , 
      CODTB4FLX varchar  (25)   , 
      CODTB5FLX varchar  (25)   , 
      CODDEPARTAMENTO varchar  (25)   , 
      CODCCUSTO varchar  (25)   , 
      CODFILIAL int   , 
      CODCOLCFO nvarchar(max)   NOT NULL  , 
      CODBANCOCOBRANCA varchar  (3)   , 
      CNABCARTEIRA int   , 
      CODCPG varchar  (5)   , 
      CODVEN varchar  (16)   , 
      PERCENTUALDESC nvarchar(max)   , 
      CODRPR varchar  (15)   , 
      CODTDO varchar  (10)   , 
      CODCOLCXA nvarchar(max)   , 
      CODCXA varchar  (10)   , 
      CODTRA varchar  (5)   , 
      TIPOCONTABILLAN int   , 
      CODCPGVENDA varchar  (5)   , 
      CIFFOB int   , 
      CODTRA2 varchar  (5)   , 
      DIASVENCSEMANA int   , 
      PERCDESCCOMPRA nvarchar(max)   , 
      CODIGOINSS varchar  (10)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON datetime2   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON datetime2   , 
      IDITEMCONTABIL int   , 
      IDCONVENIO int   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE FTCF( 
      CODCOLIGADA nvarchar(max)   NOT NULL  , 
      id  INT IDENTITY    NOT NULL  , 
      CODTCF varchar  (25)   NOT NULL  , 
      DESCRICAO varchar  (40)   , 
      CAMPOLIVRE varchar  (40)   , 
      CODSEGM varchar  (5)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON datetime2   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON datetime2   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE GCCUSTO( 
      USE nvarchar(max)   NOT NULL  , 
      ID  INT IDENTITY    NOT NULL  , 
      CODCCUSTO varchar  (25)   NOT NULL  , 
      NOME varchar  (60)   , 
      CODCOLCONTAGER nvarchar(max)   , 
      CODCONTAGER nvarchar(max)   , 
      CODCOLCONTA nvarchar(max)   , 
      CODCONTA nvarchar(max)   , 
      CODREDUZIDO varchar  (25)   NOT NULL  , 
      CAMPOLIVRE varchar  (100)   , 
      ATIVO bit   , 
      PERMITELANC bit   , 
      CODCLASSIFICA varchar  (10)   , 
      ENVIASPED bit   NOT NULL  , 
      DATAINCLUSAO datetime2   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON datetime2   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON datetime2   , 
      RESPONSAVEL int   , 
 PRIMARY KEY (ID)) ; 

CREATE TABLE GETD( 
      id  INT IDENTITY    NOT NULL  , 
      CODETD varchar  (2)   NOT NULL  , 
      NOME varchar  (40)   , 
      NACIONAL varchar  (1)   , 
      CODIGOSINIEF varchar  (4)   , 
      IDPAIS int   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON datetime2   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON datetime2   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE GMUNICIPIO( 
      id  INT IDENTITY    NOT NULL  , 
      CODMUNICIPIO varchar  (20)   NOT NULL  , 
      CODETDMUNICIPIO varchar  (2)   NOT NULL  , 
      NOMEMUNICIPIO varchar  (32)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON datetime2   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON datetime2   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE GPAIS( 
      IDPAIS  INT IDENTITY    NOT NULL  , 
      CODPAIS varchar  (5)   NOT NULL  , 
      DESCRICAO varchar  (60)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON datetime2   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON datetime2   , 
 PRIMARY KEY (IDPAIS)) ; 

CREATE TABLE orcamentos_cnc( 
      row_num  INT IDENTITY    , 
      coligada varchar  (255)   , 
      orcamento varchar  (255)   , 
      data_emissao date   , 
      cod_cliente char  (7)   , 
      cliente varchar  (255)   , 
      dias int   , 
      id_objeto varchar  (255)   , 
      objeto varchar  (255)   , 
      centro_custo varchar  (255)   , 
      os varchar  (255)   , 
      tecnico varchar  (255)   , 
      status varchar  (255)   , 
      cor_status varchar  (10)   , 
      intervalo varchar  (20)   , 
      qtde int   , 
 PRIMARY KEY (row_num)) ; 

CREATE TABLE orcamentos_comercio( 
      row_num  INT IDENTITY    , 
      coligada varchar  (255)   , 
      orcamento varchar  (255)   , 
      data_emissao date   , 
      cod_cliente char  (7)   , 
      cliente varchar  (255)   , 
      dias int   , 
      id_objeto varchar  (255)   , 
      objeto varchar  (255)   , 
      centro_custo varchar  (255)   , 
      os varchar  (255)   , 
      tecnico varchar  (255)   , 
      status varchar  (255)   , 
      cor_status varchar  (10)   , 
      intervalo varchar  (25)   , 
      qtde int   , 
 PRIMARY KEY (row_num)) ; 

CREATE TABLE TCPG( 
      id  INT IDENTITY    NOT NULL  , 
      CODCOLIGADA nvarchar(max)   NOT NULL  , 
      CODCPG varchar  (5)   NOT NULL  , 
      NOME varchar  (100)   , 
      ARREDPRIMOUULT varchar  (1)   , 
      ARREDDEZOUCENT varchar  (1)   , 
      NUMVETCONDICOES int   , 
      VALORPAGAMENTO1 nvarchar(max)   , 
      QUANTASVEZES1 int   , 
      PERIODOEMDIAS1 int   , 
      PRAZO1 int   , 
      CONTAGEMDIAS1 varchar  (1)   , 
      TIPO1 varchar  (1)   , 
      VALORPAGAMENTO2 nvarchar(max)   , 
      QUANTASVEZES2 int   , 
      PERIODOEMDIAS2 int   , 
      PRAZO2 int   , 
      CONTAGEMDIAS2 varchar  (1)   , 
      TIPO2 varchar  (1)   , 
      VALORPAGAMENTO3 nvarchar(max)   , 
      QUANTASVEZES3 int   , 
      PERIODOEMDIAS3 int   , 
      PRAZO3 int   , 
      CONTAGEMDIAS3 varchar  (1)   , 
      TIPO3 varchar  (1)   , 
      VALORPAGAMENTO4 nvarchar(max)   , 
      QUANTASVEZES4 int   , 
      PERIODOEMDIAS4 int   , 
      PRAZO4 int   , 
      CONTAGEMDIAS4 varchar  (1)   , 
      TIPO4 varchar  (1)   , 
      VALORPAGAMENTO5 nvarchar(max)   , 
      QUANTASVEZES5 int   , 
      PERIODOEMDIAS5 int   , 
      PRAZO5 int   , 
      CONTAGEMDIAS5 varchar  (1)   , 
      TIPO5 varchar  (1)   , 
      DEFLATOR nvarchar(max)   , 
      APLICACAOFRM varchar  (1)   , 
      CODFRMPRECO1 varchar  (8)   , 
      CODFRMPRECO2 varchar  (8)   , 
      DIACARENCIA int   , 
      TAXAJUROS nvarchar(max)   , 
      JUROSCOMPOSTO nvarchar(max)   , 
      PLANOPAGTO int   , 
      CAPITALIZMENSAL nvarchar(max)   , 
      PLANOCOMPRA nvarchar(max)   , 
      PLANOVENDA nvarchar(max)   , 
      DIASVENCSEMANA int   , 
      CODFRMPRIMPARCELA varchar  (8)   , 
      INATIVO int   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON datetime2   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON datetime2   , 
      IDFORMAPAGTO int   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE TRPR( 
      id  INT IDENTITY    NOT NULL  , 
      CODCOLIGADA nvarchar(max)   NOT NULL  , 
      CODRPR varchar  (15)   NOT NULL  , 
      NOME varchar  (40)   , 
      SIGLA varchar  (5)   , 
      NOMEFANTASIA varchar  (20)   , 
      RUA varchar  (100)   , 
      NUMERO int   , 
      COMPLEMENTO nvarchar(max)   , 
      BAIRRO nvarchar(max)   , 
      CIDADE nvarchar(max)   , 
      CODETD varchar  (2)   , 
      CEP nvarchar(max)   , 
      CGC varchar  (20)   , 
      INSCRESTADUAL varchar  (20)   , 
      CONTATO varchar  (20)   , 
      TELEFONE varchar  (15)   , 
      FAX varchar  (15)   , 
      RUAPGTO varchar  (100)   , 
      NUMEROPGTO int   , 
      COMPLEMENTOPGTO nvarchar(max)   , 
      BAIRROPGTO nvarchar(max)   , 
      CIDADEPGTO nvarchar(max)   , 
      CODETDPGTO varchar  (2)   , 
      CEPPGTO nvarchar(max)   , 
      PERCENTCOMISSAO nvarchar(max)   , 
      FATCLIENTEDIRETO int   , 
      DIAFATURAMENTO int   , 
      PERCENTREPASSE nvarchar(max)   , 
      CODTB1FLX varchar  (25)   , 
      CODTB2FLX varchar  (25)   , 
      CODTB3FLX varchar  (25)   , 
      CODTB4FLX varchar  (25)   , 
      CODTB5FLX varchar  (25)   , 
      CLCONTABIL varchar  (15)   , 
      INATIVO nvarchar(max)   , 
      HOMEPAGE varchar  (80)   , 
      EMAIL varchar  (40)   , 
      CELULAR varchar  (15)   , 
      PAIS varchar  (20)   , 
      CODUSUARIO varchar  (20)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON datetime2   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON datetime2   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE TTRA( 
      USE nvarchar(max)   NOT NULL  , 
      id  INT IDENTITY    NOT NULL  , 
      CODTRA varchar  (5)   NOT NULL  , 
      NOME varchar  (40)   , 
      RUA varchar  (100)   , 
      NUMERO varchar  (8)   , 
      COMPLEMENTO nvarchar(max)   , 
      BAIRRO nvarchar(max)   , 
      CIDADE nvarchar(max)   , 
      CODETD varchar  (2)   , 
      CEP nvarchar(max)   , 
      CGC varchar  (20)   , 
      INSCRESTADUAL varchar  (20)   , 
      CONTATO varchar  (30)   , 
      TELEFONE varchar  (15)   , 
      TELEX varchar  (15)   , 
      FAX varchar  (15)   , 
      LIVRE varchar  (20)   , 
      NOMEFANTASIA varchar  (60)   , 
      PAIS varchar  (20)   , 
      CEI varchar  (20)   , 
      INSCRMUNICIPAL varchar  (20)   , 
      INATIVO int   , 
      EMAIL varchar  (60)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON datetime2   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON datetime2   , 
      CODMUNICIPIO varchar  (20)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE TVEN( 
      CODCOLIGADA nvarchar(max)   NOT NULL  , 
      id  INT IDENTITY    NOT NULL  , 
      CODVEN varchar  (16)   NOT NULL  , 
      NOME varchar  (80)   , 
      CARGO varchar  (30)   , 
      CODFILIAL int   , 
      CODLOC varchar  (15)   , 
      COMISSAO1 nvarchar(max)   , 
      COMISSAO2 nvarchar(max)   , 
      COMISSAO3 nvarchar(max)   , 
      CODPESSOA int   , 
      VENDECOMPRA int   , 
      CODUSUARIO varchar  (20)   , 
      SENHA varchar  (80)   , 
      INATIVO nvarchar(max)   , 
      PFVENDEDOR nvarchar(max)   , 
      PFCAIXA nvarchar(max)   , 
      PFSUPERVISOR nvarchar(max)   , 
      PFGERENTE nvarchar(max)   , 
      IDFUNCIONARIO int   NOT NULL  , 
      COMISSAO4 nvarchar(max)   , 
      DESCMAXIMO nvarchar(max)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON datetime2   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON datetime2   , 
 PRIMARY KEY (id)) ; 

 
 