CREATE TABLE DTIPOBAIRRO( 
      DESCRICAO varchar  (20)   NOT NULL  , 
      CODIGO  SERIAL    NOT NULL  , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON timestamp   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON timestamp   , 
 PRIMARY KEY (CODIGO)) ; 

CREATE TABLE DTIPORUA( 
      DESCRICAO varchar  (20)   NOT NULL  , 
      CODIGO  SERIAL    NOT NULL  , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON timestamp   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON timestamp   , 
 PRIMARY KEY (CODIGO)) ; 

CREATE TABLE FCFO( 
      id  SERIAL    NOT NULL  , 
      CODCFO varchar  (25)   NOT NULL  , 
      USE text   NOT NULL  , 
      NOMEFANTASIA varchar  (100)   , 
      NOME varchar  (100)   , 
      CGCCFO varchar  (20)   , 
      PAGREC integer   NOT NULL  , 
      RUA varchar  (100)   , 
      NUMERO varchar  (8)   , 
      COMPLEMENTO text   , 
      BAIRRO text   , 
      CIDADE text   , 
      CODETD varchar  (2)   , 
      CEP text   , 
      TELEFONE varchar  (15)   , 
      RUAPGTO varchar  (100)   , 
      NUMEROPGTO varchar  (8)   , 
      COMPLEMENTOPGTO text   , 
      BAIRROPGTO text   , 
      CIDADEPGTO text   , 
      CODETDPGTO varchar  (2)   , 
      CEPPGTO text   , 
      TELEFONEPGTO varchar  (15)   , 
      RUAENTREGA varchar  (100)   , 
      NUMEROENTREGA varchar  (8)   , 
      COMPLEMENTREGA text   , 
      BAIRROENTREGA text   , 
      CIDADEENTREGA text   , 
      CODETDENTREGA varchar  (2)   , 
      CEPENTREGA text   , 
      TELEFONEENTREGA varchar  (15)   , 
      FAX varchar  (15)   , 
      TELEX varchar  (15)   , 
      EMAIL varchar  (250)   , 
      CONTATO varchar  (40)   , 
      CODTCF varchar  (25)   , 
      ATIVO integer   NOT NULL  , 
      LIMITECREDITO text   , 
      VALORULTIMOLAN text   , 
      TIPOINSCRCNAB integer   , 
      DATAULTALTERACAO timestamp   , 
      DATACRIACAO timestamp   , 
      DATAULTMOVIMENTO timestamp   , 
      CONTEVENTOCONTAB integer   , 
      CAMPOLIVRE varchar  (40)   , 
      CAMPOALFAOP1 varchar  (40)   , 
      CAMPOALFAOP2 varchar  (40)   , 
      CAMPOALFAOP3 varchar  (40)   , 
      VALOROP1 text   , 
      VALOROP2 text   , 
      VALOROP3 text   , 
      DATAOP1 timestamp   , 
      DATAOP2 timestamp   , 
      DATAOP3 timestamp   , 
      CODTRA varchar  (5)   , 
      CHAPA varchar  (16)   , 
      STATUSCOTACAO varchar  (1)   , 
      DTINICATIVIDADES timestamp   , 
      PATRIMONIO text   , 
      NUMFUNCIONARIOS integer   , 
      CODCOLCHAVESESTRANG integer   , 
      CODCOLTCF integer   , 
      FAXDEDICADO integer   , 
      CODMUNICIPIO varchar  (20)   , 
      CODCOLCONTAGER integer   , 
      CODCONTAGER text   , 
      FORMAPAGAMENTO integer   , 
      IDENTPORCNPJ text   , 
      INSCRMUNICIPAL varchar  (20)   , 
      PESSOAFISOUJUR varchar  (1)   NOT NULL  , 
      CONTATOPGTO varchar  (40)   , 
      CONTATOENTREGA varchar  (40)   , 
      PAIS varchar  (20)   , 
      PAISPAGTO varchar  (20)   , 
      PAISENTREGA varchar  (20)   , 
      ULTIMODOCUMENTO varchar  (40)   , 
      CONTRIBUINTE integer   , 
      CFOIMOB integer   , 
      TIPODOC varchar  (1)   , 
      CODFINALIDADE integer   , 
      AGRUPCOB char  (1)   , 
      CODCARGO varchar  (3)   , 
      CODVINCULO char  (1)   , 
      ENDCOBC char  (1)   , 
      CIDENTIDADE varchar  (20)   , 
      CI_ORGAO varchar  (15)   , 
      CI_UF varchar  (2)   , 
      CODPROF integer   , 
      CODPAGTOGPS varchar  (5)   , 
      FAXENTREGA varchar  (15)   , 
      EMAILENTREGA varchar  (250)   , 
      FAXPGTO varchar  (15)   , 
      EMAILPGTO varchar  (250)   , 
      SATISFACAO integer   , 
      VALFRETE text   , 
      TPTOMADOR integer   , 
      CONTRIBUINTEISS integer   , 
      NUMDEPENDENTES integer   , 
      EMPRESA varchar  (60)   , 
      ESTADOCIVIL varchar  (1)   , 
      CODCOLCXA text   , 
      CODCXA varchar  (10)   , 
      PRODUTORRURAL boolean   , 
      USUARIOALTERACAO varchar  (20)   , 
      SUFRAMA varchar  (14)   , 
      CODMUNICIPIOPGTO varchar  (20)   , 
      CODMUNICIPIOENTREGA varchar  (20)   , 
      ORGAOPUBLICO integer   , 
      TELEFONECOMERCIAL varchar  (15)   , 
      CAIXAPOSTAL varchar  (10)   , 
      CAIXAPOSTALENTREGA varchar  (10)   , 
      CAIXAPOSTALPAGAMENTO varchar  (10)   , 
      CATEGORIAAUTONOMO integer   , 
      CBOAUTONOMO varchar  (10)   , 
      CIAUTONOMO varchar  (11)   , 
      IDCFO integer   NOT NULL  , 
      CODIGOINSS varchar  (10)   , 
      VROUTRASDEDUCOESIRRF text   , 
      CODRECEITA varchar  (10)   , 
      CEI varchar  (20)   , 
      OPTANTEPELOSIMPLES integer   , 
      TIPORUA integer   , 
      TIPOBAIRRO integer   , 
      REGIMEISS varchar  (1)   , 
      RETENCAOISS integer   , 
      DTNASCIMENTO timestamp   , 
      USUARIOCRIACAO varchar  (20)   , 
      TIPOOPCOMBUSTIVEL integer   , 
      INSCRESTADUALST varchar  (20)   , 
      LOCALIDADE varchar  (40)   , 
      LOCALIDADEPGTO varchar  (40)   , 
      LOCALIDADEENTREGA varchar  (40)   , 
      TIPORUAPGTO integer   , 
      TIPORUAENTREGA integer   , 
      TIPOBAIRROPGTO integer   , 
      TIPOBAIRROENTREGA integer   , 
      PORTE integer   , 
      RAMOATIV integer   NOT NULL  , 
      NIT varchar  (15)   , 
      CEPCAIXAPOSTAL text   , 
      NUMDIASATRASO integer   , 
      IDPAIS integer   , 
      IDPAISPGTO integer   , 
      IDPAISENTREGA integer   , 
      TIPOCONTRIBUINTEINSS integer   NOT NULL  , 
      NACIONALIDADE integer   NOT NULL  , 
      CODCOLCFOFISCAL text   , 
      IDCFOFISCAL integer   , 
      EMAILFISCAL varchar  (250)   , 
      CALCULAAVP integer   NOT NULL  , 
      CODUSUARIOACESSO varchar  (20)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON timestamp   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON timestamp   , 
      IDINTEGRACAO varchar  (100)   , 
      USARCUMULATRETENCAOPAGAR integer   , 
      NIF varchar  (50)   , 
      SITUACAONIF integer   , 
      TIPORENDIMENTO varchar  (3)   , 
      FORMATRIBUTACAO varchar  (2)   , 
      INDNATRET varchar  (5)   , 
      DOCUMENTOESTRANGEIRO varchar  (30)   , 
      TPLOTACAO_OLD varchar  (2)   , 
      INOVAR_AUTO integer   , 
      FILIALFINANCEIRA integer   , 
      TOMADORFOLHA integer   , 
      CNAEPREP varchar  (7)   , 
      PERCENTACIDTRAB text   , 
      CODCOLFORMULA text   , 
      FORMULAVALDEDUCAOVARIAVEL varchar  (8)   , 
      APLICFORMULA varchar  (1)   , 
      CODCFOCOLINTEGRACAO text   , 
      CODCFOINTEGRACAO varchar  (25)   , 
      DIGVERIFICDEBAUTOMATICO varchar  (1)   , 
      CODLOJA varchar  (8)   , 
      CODFILIALINTEGRACAO integer   , 
      CODEXTERNO varchar  (25)   , 
      TIPOCLIENTE varchar  (2)   , 
      CONSIDERAFILIALOBRA integer   , 
      CODFILIALOBRA integer   , 
      TIPOCONTROLEPONTO integer   , 
      FAP text   , 
      CODCOLIGADAFILIALOBRA text   , 
      OBRAPROPRIA integer   , 
      ENTIDADEEXECUTORAPAA integer   NOT NULL  , 
      APOSENTADOOUPENSIONISTA integer   NOT NULL  , 
      CODCATEGORIAESOCIAL integer   , 
      CNPJRURAL varchar  (20)   , 
      CODIGOCAEPF varchar  (18)   , 
      ISENTOTRIBUTOS text   , 
      SOCIOCOOPERADO integer   NOT NULL  , 
 PRIMARY KEY (id)) ; 

CREATE TABLE FCFOCONTATO( 
      IDINTEGRACAO  SERIAL    NOT NULL  , 
      IDCONTATO integer   NOT NULL  , 
      CODCOLIGADA text   NOT NULL  , 
      CODCFO varchar  (25)   NOT NULL  , 
      NOME varchar  (50)   NOT NULL  , 
      EMAIL varchar  (80)   , 
      TELEFONE varchar  (15)   , 
      RAMAL varchar  (6)   , 
      FAX varchar  (15)   , 
      FUNCAO varchar  (50)   , 
      OBSERVACAO varchar  (80)   , 
      CODUSUARIO varchar  (20)   , 
      RUA varchar  (100)   , 
      NUMERO varchar  (8)   , 
      COMPLEMENTO text   , 
      BAIRRO text   , 
      CIDADE text   , 
      CODETD varchar  (2)   , 
      CEP text   , 
      PAIS varchar  (20)   , 
      USUARIOALTERACAO varchar  (20)   , 
      DATAALTERACAO timestamp   , 
      ATIVO integer   , 
      DATANASCIMENTO timestamp   , 
      DEFAUTPARAEMAIL integer   , 
      CODAPLIC varchar  (2)   , 
      CODMUNICIPIO varchar  (20)   , 
      LOCALIDADE varchar  (40)   , 
      CODUSUARIOACESSO varchar  (20)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON timestamp   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON timestamp   , 
 PRIMARY KEY (IDINTEGRACAO)) ; 

CREATE TABLE FCFODEF( 
      CODCOLIGADA text   NOT NULL  , 
      id  SERIAL    NOT NULL  , 
      CODCFO varchar  (25)   NOT NULL  , 
      CODTB1FLX varchar  (25)   , 
      CODTB2FLX varchar  (25)   , 
      CODTB3FLX varchar  (25)   , 
      CODTB4FLX varchar  (25)   , 
      CODTB5FLX varchar  (25)   , 
      CODDEPARTAMENTO varchar  (25)   , 
      CODCCUSTO varchar  (25)   , 
      CODFILIAL integer   , 
      CODCOLCFO text   NOT NULL  , 
      CODBANCOCOBRANCA varchar  (3)   , 
      CNABCARTEIRA integer   , 
      CODCPG varchar  (5)   , 
      CODVEN varchar  (16)   , 
      PERCENTUALDESC text   , 
      CODRPR varchar  (15)   , 
      CODTDO varchar  (10)   , 
      CODCOLCXA text   , 
      CODCXA varchar  (10)   , 
      CODTRA varchar  (5)   , 
      TIPOCONTABILLAN integer   , 
      CODCPGVENDA varchar  (5)   , 
      CIFFOB integer   , 
      CODTRA2 varchar  (5)   , 
      DIASVENCSEMANA integer   , 
      PERCDESCCOMPRA text   , 
      CODIGOINSS varchar  (10)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON timestamp   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON timestamp   , 
      IDITEMCONTABIL integer   , 
      IDCONVENIO integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE FTCF( 
      CODCOLIGADA text   NOT NULL  , 
      id  SERIAL    NOT NULL  , 
      CODTCF varchar  (25)   NOT NULL  , 
      DESCRICAO varchar  (40)   , 
      CAMPOLIVRE varchar  (40)   , 
      CODSEGM varchar  (5)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON timestamp   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON timestamp   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE GCCUSTO( 
      USE text   NOT NULL  , 
      ID  SERIAL    NOT NULL  , 
      CODCCUSTO varchar  (25)   NOT NULL  , 
      NOME varchar  (60)   , 
      CODCOLCONTAGER text   , 
      CODCONTAGER text   , 
      CODCOLCONTA text   , 
      CODCONTA text   , 
      CODREDUZIDO varchar  (25)   NOT NULL  , 
      CAMPOLIVRE varchar  (100)   , 
      ATIVO boolean   , 
      PERMITELANC boolean   , 
      CODCLASSIFICA varchar  (10)   , 
      ENVIASPED boolean   NOT NULL  , 
      DATAINCLUSAO timestamp   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON timestamp   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON timestamp   , 
      RESPONSAVEL integer   , 
 PRIMARY KEY (ID)) ; 

CREATE TABLE GETD( 
      id  SERIAL    NOT NULL  , 
      CODETD varchar  (2)   NOT NULL  , 
      NOME varchar  (40)   , 
      NACIONAL varchar  (1)   , 
      CODIGOSINIEF varchar  (4)   , 
      IDPAIS integer   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON timestamp   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON timestamp   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE GMUNICIPIO( 
      id  SERIAL    NOT NULL  , 
      CODMUNICIPIO varchar  (20)   NOT NULL  , 
      CODETDMUNICIPIO varchar  (2)   NOT NULL  , 
      NOMEMUNICIPIO varchar  (32)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON timestamp   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON timestamp   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE GPAIS( 
      IDPAIS  SERIAL    NOT NULL  , 
      CODPAIS varchar  (5)   NOT NULL  , 
      DESCRICAO varchar  (60)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON timestamp   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON timestamp   , 
 PRIMARY KEY (IDPAIS)) ; 

CREATE TABLE orcamentos_cnc( 
      row_num  SERIAL    , 
      coligada varchar  (255)   , 
      orcamento varchar  (255)   , 
      data_emissao date   , 
      cod_cliente char  (7)   , 
      cliente varchar  (255)   , 
      dias integer   , 
      id_objeto varchar  (255)   , 
      objeto varchar  (255)   , 
      centro_custo varchar  (255)   , 
      os varchar  (255)   , 
      tecnico varchar  (255)   , 
      status varchar  (255)   , 
      cor_status varchar  (10)   , 
      intervalo varchar  (20)   , 
      qtde integer   , 
 PRIMARY KEY (row_num)) ; 

CREATE TABLE orcamentos_comercio( 
      row_num  SERIAL    , 
      coligada varchar  (255)   , 
      orcamento varchar  (255)   , 
      data_emissao date   , 
      cod_cliente char  (7)   , 
      cliente varchar  (255)   , 
      dias integer   , 
      id_objeto varchar  (255)   , 
      objeto varchar  (255)   , 
      centro_custo varchar  (255)   , 
      os varchar  (255)   , 
      tecnico varchar  (255)   , 
      status varchar  (255)   , 
      cor_status varchar  (10)   , 
      intervalo varchar  (25)   , 
      qtde integer   , 
 PRIMARY KEY (row_num)) ; 

CREATE TABLE TCPG( 
      id  SERIAL    NOT NULL  , 
      CODCOLIGADA text   NOT NULL  , 
      CODCPG varchar  (5)   NOT NULL  , 
      NOME varchar  (100)   , 
      ARREDPRIMOUULT varchar  (1)   , 
      ARREDDEZOUCENT varchar  (1)   , 
      NUMVETCONDICOES integer   , 
      VALORPAGAMENTO1 text   , 
      QUANTASVEZES1 integer   , 
      PERIODOEMDIAS1 integer   , 
      PRAZO1 integer   , 
      CONTAGEMDIAS1 varchar  (1)   , 
      TIPO1 varchar  (1)   , 
      VALORPAGAMENTO2 text   , 
      QUANTASVEZES2 integer   , 
      PERIODOEMDIAS2 integer   , 
      PRAZO2 integer   , 
      CONTAGEMDIAS2 varchar  (1)   , 
      TIPO2 varchar  (1)   , 
      VALORPAGAMENTO3 text   , 
      QUANTASVEZES3 integer   , 
      PERIODOEMDIAS3 integer   , 
      PRAZO3 integer   , 
      CONTAGEMDIAS3 varchar  (1)   , 
      TIPO3 varchar  (1)   , 
      VALORPAGAMENTO4 text   , 
      QUANTASVEZES4 integer   , 
      PERIODOEMDIAS4 integer   , 
      PRAZO4 integer   , 
      CONTAGEMDIAS4 varchar  (1)   , 
      TIPO4 varchar  (1)   , 
      VALORPAGAMENTO5 text   , 
      QUANTASVEZES5 integer   , 
      PERIODOEMDIAS5 integer   , 
      PRAZO5 integer   , 
      CONTAGEMDIAS5 varchar  (1)   , 
      TIPO5 varchar  (1)   , 
      DEFLATOR text   , 
      APLICACAOFRM varchar  (1)   , 
      CODFRMPRECO1 varchar  (8)   , 
      CODFRMPRECO2 varchar  (8)   , 
      DIACARENCIA integer   , 
      TAXAJUROS text   , 
      JUROSCOMPOSTO text   , 
      PLANOPAGTO integer   , 
      CAPITALIZMENSAL text   , 
      PLANOCOMPRA text   , 
      PLANOVENDA text   , 
      DIASVENCSEMANA integer   , 
      CODFRMPRIMPARCELA varchar  (8)   , 
      INATIVO integer   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON timestamp   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON timestamp   , 
      IDFORMAPAGTO integer   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE TRPR( 
      id  SERIAL    NOT NULL  , 
      CODCOLIGADA text   NOT NULL  , 
      CODRPR varchar  (15)   NOT NULL  , 
      NOME varchar  (40)   , 
      SIGLA varchar  (5)   , 
      NOMEFANTASIA varchar  (20)   , 
      RUA varchar  (100)   , 
      NUMERO integer   , 
      COMPLEMENTO text   , 
      BAIRRO text   , 
      CIDADE text   , 
      CODETD varchar  (2)   , 
      CEP text   , 
      CGC varchar  (20)   , 
      INSCRESTADUAL varchar  (20)   , 
      CONTATO varchar  (20)   , 
      TELEFONE varchar  (15)   , 
      FAX varchar  (15)   , 
      RUAPGTO varchar  (100)   , 
      NUMEROPGTO integer   , 
      COMPLEMENTOPGTO text   , 
      BAIRROPGTO text   , 
      CIDADEPGTO text   , 
      CODETDPGTO varchar  (2)   , 
      CEPPGTO text   , 
      PERCENTCOMISSAO text   , 
      FATCLIENTEDIRETO integer   , 
      DIAFATURAMENTO integer   , 
      PERCENTREPASSE text   , 
      CODTB1FLX varchar  (25)   , 
      CODTB2FLX varchar  (25)   , 
      CODTB3FLX varchar  (25)   , 
      CODTB4FLX varchar  (25)   , 
      CODTB5FLX varchar  (25)   , 
      CLCONTABIL varchar  (15)   , 
      INATIVO text   , 
      HOMEPAGE varchar  (80)   , 
      EMAIL varchar  (40)   , 
      CELULAR varchar  (15)   , 
      PAIS varchar  (20)   , 
      CODUSUARIO varchar  (20)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON timestamp   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON timestamp   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE TTRA( 
      USE text   NOT NULL  , 
      id  SERIAL    NOT NULL  , 
      CODTRA varchar  (5)   NOT NULL  , 
      NOME varchar  (40)   , 
      RUA varchar  (100)   , 
      NUMERO varchar  (8)   , 
      COMPLEMENTO text   , 
      BAIRRO text   , 
      CIDADE text   , 
      CODETD varchar  (2)   , 
      CEP text   , 
      CGC varchar  (20)   , 
      INSCRESTADUAL varchar  (20)   , 
      CONTATO varchar  (30)   , 
      TELEFONE varchar  (15)   , 
      TELEX varchar  (15)   , 
      FAX varchar  (15)   , 
      LIVRE varchar  (20)   , 
      NOMEFANTASIA varchar  (60)   , 
      PAIS varchar  (20)   , 
      CEI varchar  (20)   , 
      INSCRMUNICIPAL varchar  (20)   , 
      INATIVO integer   , 
      EMAIL varchar  (60)   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON timestamp   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON timestamp   , 
      CODMUNICIPIO varchar  (20)   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE TVEN( 
      CODCOLIGADA text   NOT NULL  , 
      id  SERIAL    NOT NULL  , 
      CODVEN varchar  (16)   NOT NULL  , 
      NOME varchar  (80)   , 
      CARGO varchar  (30)   , 
      CODFILIAL integer   , 
      CODLOC varchar  (15)   , 
      COMISSAO1 text   , 
      COMISSAO2 text   , 
      COMISSAO3 text   , 
      CODPESSOA integer   , 
      VENDECOMPRA integer   , 
      CODUSUARIO varchar  (20)   , 
      SENHA varchar  (80)   , 
      INATIVO text   , 
      PFVENDEDOR text   , 
      PFCAIXA text   , 
      PFSUPERVISOR text   , 
      PFGERENTE text   , 
      IDFUNCIONARIO integer   NOT NULL  , 
      COMISSAO4 text   , 
      DESCMAXIMO text   , 
      RECCREATEDBY varchar  (50)   , 
      RECCREATEDON timestamp   , 
      RECMODIFIEDBY varchar  (50)   , 
      RECMODIFIEDON timestamp   , 
 PRIMARY KEY (id)) ; 

 
 